

name: cattleclassifier
description: Cattle Classifier in Flutter using TensorFlow Lite
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  collection: ^1.16.0
  image: ^3.2.2
  tflite_flutter: ^0.9.0
  firebase_auth: ^4.19.2 # add this line
  firebase_core: ^2.30.0
  tflite_flutter_helper:
    git:
      url: https://github.com/filofan1/tflite_flutter_helper.git
      ref: 783f15e5a87126159147d8ea30b98eea9207ac70
  provider: ^6.1.2
  fluttertoast: ^8.2.5
  cloud_firestore: ^4.17.0
  path_provider: ^2.0.9
  connectivity_plus: ^2.0.2
  firebase_storage: ^11.7.2




dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:  
  - family: SquadaOne
    fonts:
      - asset: assets/SquadaOne-Regular.ttf
  - family: ContrailOne
    fonts:
      - asset: assets/ContrailOne-Regular.ttf
  - family: Roboto
    fonts:
      - asset: assets/Roboto-Light.ttf      
  
  assets:
    - assets/
